/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.util.List;

import javax.swing.JOptionPane;

import Archivos.ArchivoProductos;
import Archivos.ArchivoVentas;
import Productos.Productos;
import Productos.Venta;

public class MenuPrincipal extends javax.swing.JFrame {

    public List<Productos> productos = ArchivoProductos.LeerDatosDeArchivo();
    public List<Venta> ventas = ArchivoVentas.LeerDatosDeArchivo();

    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registroProductosBtn = new javax.swing.JButton();
        registroVentaBtn = new javax.swing.JButton();
        consultarVentaBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroProductosBtn.setText("Registro de productos");
        registroProductosBtn.setAlignmentX(161.0F);
        registroProductosBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(153, 153, 153)));
        registroProductosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProductosBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registroProductosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 30));

        registroVentaBtn.setText("Registrar una venta");
        registroVentaBtn.setAlignmentX(161.0F);
        registroVentaBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(153, 153, 153)));
        registroVentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroVentaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registroVentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 130, 30));

        consultarVentaBtn.setText("Consultar una venta");
        consultarVentaBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(153, 153, 153)));
        consultarVentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVentaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(consultarVentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 130, 30));

        salirBtn.setText("Salir");
        salirBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(153, 153, 153)));
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        jPanel1.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/hen.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/Los pollitos.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroProductosBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registroProductosBtnActionPerformed
        MenuProducto menu = new MenuProducto();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        dispose();
    }// GEN-LAST:event_registroProductosBtnActionPerformed

    private void registroVentaBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registroVentaBtnActionPerformed
        if (productos.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No se puede registrar venta sin productos existentes.", getTitle(),
                    0);
            return;
        } else {
            MenuVenta menu = new MenuVenta();
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            dispose();
        }
    }// GEN-LAST:event_registroVentaBtnActionPerformed

    private void consultarVentaBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_consultarVentaBtnActionPerformed
        if (ventas.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No se pueden consultar ventas sin haber realizado alguna.",
                    getTitle(),
                    0);
        } else {
            MenuConsultar menu = new MenuConsultar();
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            dispose();
        }
    }// GEN-LAST:event_consultarVentaBtnActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salirBtnActionPerformed
        System.exit(0);
    }// GEN-LAST:event_salirBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarVentaBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registroProductosBtn;
    private javax.swing.JButton registroVentaBtn;
    private javax.swing.JButton salirBtn;
    // End of variables declaration//GEN-END:variables
}
