/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.util.*;

import javax.swing.JOptionPane;

import Archivos.ArchivoMarcas;
import Archivos.ArchivoProductos;
import Productos.Abarrote;
import Productos.Productos;
import Productos.Verdura;

public class RegistroProducto extends javax.swing.JFrame {

    public List<String> marcas = ArchivoMarcas.LeerDatosDeArchivo();

    public RegistroProducto() {
        initComponents();
        for (String string : marcas) {
            marcasBox.addItem(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        marcasBox = new javax.swing.JComboBox<>();
        precioProducto = new javax.swing.JTextField();
        registrarProducto = new javax.swing.JButton();
        tipoProducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarBtn.setText("Regresar");
        regresarBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(153, 153, 153)));
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/hen.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoActionPerformed(evt);
            }
        });
        jPanel1.add(nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 176, -1));

        jPanel1.add(marcasBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        precioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioProductoActionPerformed(evt);
            }
        });
        jPanel1.add(precioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 176, -1));

        registrarProducto.setText("Registrar");
        registrarProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(153, 153, 153)));
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(registrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 60, 20));

        tipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verdura", "Abarrote" }));
        jPanel1.add(tipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, -1));

        jLabel2.setText("Tipo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setText("Marca:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_regresarBtnActionPerformed
        dispose();
    }// GEN-LAST:event_regresarBtnActionPerformed

    private void nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombreProductoActionPerformed

    }// GEN-LAST:event_nombreProductoActionPerformed

    private void precioProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_precioProductoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_precioProductoActionPerformed

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registrarProductoActionPerformed
        List<Productos> productos = ArchivoProductos.LeerDatosDeArchivo();
        for (Productos productos2 : productos) {
            if(nombreProducto.getText().equals(productos2.getNombre())){
                JOptionPane.showMessageDialog(rootPane, "Ya existe un producto con ese nombre.", getTitle(), 0);
                return;
            }
        }
        if (nombreProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nombre vacio.", getTitle(), 0);
            return;
        }
        try {
            if (tipoProducto.getSelectedItem().equals("Verdura")) {
                Productos verdura = new Verdura(nombreProducto.getText(), (String) marcasBox.getSelectedItem(),
                        Integer.parseInt(precioProducto.getText()));
                ArchivoProductos archivo = new ArchivoProductos();
                JOptionPane.showMessageDialog(rootPane, "Producto registrado.", getTitle(), 1);
                archivo.EscribirEnArchivo(verdura);
            } else {
                Productos abarrote = new Abarrote(nombreProducto.getText(), (String) marcasBox.getSelectedItem(),
                        Integer.parseInt(precioProducto.getText()));
                ArchivoProductos archivo = new ArchivoProductos();
                JOptionPane.showMessageDialog(rootPane, "Producto registrado.", getTitle(), 1);
                archivo.EscribirEnArchivo(abarrote);
            }
            dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato para numero incorrecto.", getTitle(), 0);
        }
    }// GEN-LAST:event_registrarProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> marcasBox;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JButton registrarProducto;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JComboBox<String> tipoProducto;
    // End of variables declaration//GEN-END:variables
}
