/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloEnvio;

import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import Menu.MenuPrincipal;
import Persona.Colaborador;
import Planilla.Planilla;
import SQL.Conexion;
import SQL.SQLColaborador;

public class EnvioServidor extends javax.swing.JFrame {

    public Connection conexion;
    public SQLColaborador conexionSQL;
    public List<Colaborador> colaboradores = new ArrayList<>();
    public HashSet<Date> fechas = new HashSet<>();

    public EnvioServidor() {
        initComponents();
        try {
            conexion = Conexion.getConnection();
            conexionSQL = new SQLColaborador(conexion);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        actualizarLista();
        actualizarSet();
        for (Date fecha : fechas) {
            fechasRegistradas.addItem(fecha.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customLayout = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        verPlanillas = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        pnlConteo = new keeptoo.KGradientPanel();
        enviarPlanilla = new com.k33ptoo.components.KButton();
        volverBtn = new com.k33ptoo.components.KButton();
        fechasRegistradas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlanillas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        verPlanillas.setBackground(new java.awt.Color(51, 51, 51));
        verPlanillas.setForeground(new java.awt.Color(204, 204, 204));
        verPlanillas.setText("Servidor");
        verPlanillas.setBorder(null);
        verPlanillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPlanillasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(verPlanillas, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(65, Short.MAX_VALUE)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(verPlanillas, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(165, Short.MAX_VALUE)));

        jSplitPane1.setLeftComponent(jPanel6);

        pnlCards.setLayout(new java.awt.CardLayout());

        pnlConteo.setkEndColor(new java.awt.Color(255, 255, 255));
        pnlConteo.setkStartColor(new java.awt.Color(153, 153, 153));
        pnlConteo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviarPlanilla.setText("Enviar");
        enviarPlanilla.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        enviarPlanilla.setkEndColor(new java.awt.Color(51, 51, 51));
        enviarPlanilla.setkHoverColor(new java.awt.Color(102, 102, 102));
        enviarPlanilla.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        enviarPlanilla.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        enviarPlanilla.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        enviarPlanilla.setkStartColor(new java.awt.Color(51, 51, 51));
        enviarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarPlanillaActionPerformed(evt);
            }
        });
        pnlConteo.add(enviarPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, -1));

        volverBtn.setText("Volver");
        volverBtn.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        volverBtn.setkEndColor(new java.awt.Color(102, 102, 102));
        volverBtn.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        volverBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        volverBtn.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        volverBtn.setkStartColor(new java.awt.Color(51, 51, 51));
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        pnlConteo.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 80, 30));

        fechasRegistradas.setBackground(new java.awt.Color(255, 255, 255));
        fechasRegistradas.setForeground(new java.awt.Color(0, 0, 0));
        fechasRegistradas
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        fechasRegistradas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fechasRegistradasItemStateChanged(evt);
            }
        });
        fechasRegistradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechasRegistradasActionPerformed(evt);
            }
        });
        pnlConteo.add(fechasRegistradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, -1));

        tablaPlanillas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(tablaPlanillas);

        pnlConteo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 400, 300));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Planilla");
        pnlConteo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        pnlCards.add(pnlConteo, "pnlConteo");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout customLayoutLayout = new javax.swing.GroupLayout(customLayout);
        customLayout.setLayout(customLayoutLayout);
        customLayoutLayout.setHorizontalGroup(
                customLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(customLayoutLayout.createSequentialGroup()
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        customLayoutLayout.setVerticalGroup(
                customLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(customLayoutLayout.createSequentialGroup()
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(customLayout, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(customLayout, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarLista() {
        try {
            colaboradores = conexionSQL.select();
            conexion.commit();
        } catch (SQLException e) {
            e.printStackTrace();
            try {
                conexion.rollback();
            } catch (SQLException e1) {
                e1.printStackTrace();
            }

        }
    }

    public void actualizarSet() {
        for (Colaborador colaborador : colaboradores) {
            fechas.add(colaborador.getFecha());
        }
    }

    private void verPlanillasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_verPlanillasActionPerformed

    }// GEN-LAST:event_verPlanillasActionPerformed

    private void enviarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enviarPlanillaActionPerformed
        Socket socket = null;
        ObjectOutputStream stream = null;
        List<Colaborador> personas = new ArrayList<>();
        Planilla planilla = new Planilla();
        try {
            socket = new Socket("localhost", 3302);
            stream = new ObjectOutputStream(socket.getOutputStream());
            for (Colaborador colaborador : colaboradores) {
                if (colaborador.getFecha().toString().equals(fechasRegistradas.getSelectedItem())) {
                    personas.add(colaborador);
                }
            }
            planilla.setColaboradores(personas);
            stream.writeObject(planilla);
            stream.close();
            socket.close();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_enviarPlanillaActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverBtnActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        dispose();
    }// GEN-LAST:event_volverBtnActionPerformed

    private void fechasRegistradasItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_fechasRegistradasItemStateChanged
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Cedula");
        modelo.addColumn("Horas");
        modelo.addColumn("Fecha");
        modelo.addColumn("Total");
        for (Colaborador colaborador : colaboradores) {
            if (colaborador.getFecha().toString().equals(fechasRegistradas.getSelectedItem())) {
                modelo.addRow(new Object[] { colaborador.getIdPersona(), colaborador.getNombre(),
                        colaborador.getApellido(), colaborador.getCedula(), colaborador.getHorasTrabajadas(),
                        colaborador.getFecha().toString(), "--" });
            }
        }
        tablaPlanillas.setModel(modelo);
    }// GEN-LAST:event_fechasRegistradasItemStateChanged

    private void fechasRegistradasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fechasRegistradasActionPerformed

    }// GEN-LAST:event_fechasRegistradasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel customLayout;
    private com.k33ptoo.components.KButton enviarPlanilla;
    private javax.swing.JComboBox<String> fechasRegistradas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlCards;
    private keeptoo.KGradientPanel pnlConteo;
    private javax.swing.JTable tablaPlanillas;
    private javax.swing.JButton verPlanillas;
    private com.k33ptoo.components.KButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
