/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloRegistro;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import Archivos.ManejoDeArchivos;
import Persona.Estudiante;
import Persona.Persona;

public class editarEstudiante extends javax.swing.JFrame {

        public ManejoDeArchivos archivo;
        public ArrayList<Persona> lista;

        public editarEstudiante() {
                initComponents();
                this.archivo = new ManejoDeArchivos();
                this.lista = archivo.LeerDatosDeArchivo();
                Estudiante estudiante = (Estudiante) usuarioEncontrado.getPersona();
                nombreEstudiante.setText(estudiante.getNombre());
                apellidosEstudiante.setText(estudiante.getApellido());
                cedulaEstudiante.setText(estudiante.getCedula());
                seccionEstudiante.setText(estudiante.getGrupo() + "");
                if (estudiante.isBeca()) {
                        becaEstudiante.setSelectedIndex(0);
                } else {
                        becaEstudiante.setSelectedIndex(1);
                }
                if (estudiante.isActividad()) {
                        estadoEstudiante.setSelectedIndex(0);
                } else {
                        estadoEstudiante.setSelectedIndex(1);
                }
                switch (estudiante.getEdad()) {
                        case 13:
                                edadEstudiante.setSelectedIndex(0);
                                break;
                        case 14:
                                edadEstudiante.setSelectedIndex(1);
                                break;
                        case 15:
                                edadEstudiante.setSelectedIndex(2);
                                break;
                        case 16:
                                edadEstudiante.setSelectedIndex(3);
                                break;
                        case 17:
                                edadEstudiante.setSelectedIndex(4);
                                break;
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                becaEstudiante = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                seccionEstudiante = new javax.swing.JTextField();
                nombreEstudiante = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                cedulaEstudiante = new javax.swing.JTextField();
                apellidosEstudiante = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                estadoEstudiante = new javax.swing.JComboBox<>();
                jLabel5 = new javax.swing.JLabel();
                edadEstudiante = new javax.swing.JComboBox<>();
                jLabel4 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                editarBtn = new com.k33ptoo.components.KButton();
                volver = new com.k33ptoo.components.KButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(51, 51, 51));
                jPanel1.setForeground(new java.awt.Color(51, 51, 51));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 431, Short.MAX_VALUE));

                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                becaEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
                becaEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
                becaEstudiante.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                becaEstudianteActionPerformed(evt);
                        }
                });
                jPanel2.add(becaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 264, 96, -1));

                jLabel3.setText("Apellidos:");
                jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, -1, -1));

                jLabel2.setText("Edad:");
                jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, -1, -1));

                jLabel1.setText("Nombre:");
                jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, -1, -1));

                seccionEstudiante.setBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                                                null, null, new java.awt.Color(102, 102, 102)));
                jPanel2.add(seccionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 219, 279, -1));

                nombreEstudiante.setBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                                                null, null, new java.awt.Color(153, 153, 153)));
                jPanel2.add(nombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 59, 279, -1));

                jLabel9.setText("Seccion:");
                jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, -1, -1));

                cedulaEstudiante.setBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                                                null, null, new java.awt.Color(102, 102, 102)));
                jPanel2.add(cedulaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 179, 279, -1));

                apellidosEstudiante.setBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                                                null, null, new java.awt.Color(153, 153, 153)));
                jPanel2.add(apellidosEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 99, 279, -1));

                jLabel6.setText("Cedula:");
                jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, -1, -1));

                estadoEstudiante.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
                estadoEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                estadoEstudiante.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                estadoEstudianteActionPerformed(evt);
                        }
                });
                jPanel2.add(estadoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 304, 96, -1));

                jLabel5.setText("Estado:");
                jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 307, -1, -1));

                edadEstudiante.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "13", "14", "15", "16", "17" }));
                edadEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                edadEstudiante.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                edadEstudianteActionPerformed(evt);
                        }
                });
                jPanel2.add(edadEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 139, 60, -1));

                jLabel4.setText("Beca:");
                jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, -1, -1));

                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(51, 51, 51));
                jLabel7.setText("Editar ");
                jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 16, -1, -1));

                editarBtn.setText("Editar");
                editarBtn.setkBackGroundColor(new java.awt.Color(255, 255, 255));
                editarBtn.setkEndColor(new java.awt.Color(51, 51, 51));
                editarBtn.setkHoverColor(new java.awt.Color(102, 102, 102));
                editarBtn.setkHoverEndColor(new java.awt.Color(102, 102, 102));
                editarBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
                editarBtn.setkHoverStartColor(new java.awt.Color(102, 102, 102));
                editarBtn.setkStartColor(new java.awt.Color(51, 51, 51));
                editarBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                editarBtnActionPerformed(evt);
                        }
                });
                jPanel2.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 150, -1));

                volver.setText("Volver");
                volver.setkBackGroundColor(new java.awt.Color(51, 51, 51));
                volver.setkEndColor(new java.awt.Color(102, 102, 102));
                volver.setkHoverEndColor(new java.awt.Color(102, 102, 102));
                volver.setkHoverForeGround(new java.awt.Color(255, 255, 255));
                volver.setkHoverStartColor(new java.awt.Color(102, 102, 102));
                volver.setkStartColor(new java.awt.Color(51, 51, 51));
                volver.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                volverActionPerformed(evt);
                        }
                });
                jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 80, 30));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void volverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverActionPerformed
                dispose();
        }// GEN-LAST:event_volverActionPerformed

        private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarBtnActionPerformed
                if (revisarEstudiante()) {
                        return;
                } else {
                        try {
                                int edad = 0;
                                boolean beca = false, estado = false;
                                switch (edadEstudiante.getSelectedIndex()) {
                                        case 0:
                                                edad = 13;
                                                break;
                                        case 1:
                                                edad = 14;
                                                break;
                                        case 2:
                                                edad = 15;
                                                break;
                                        case 3:
                                                edad = 16;
                                                break;
                                        case 4:
                                                edad = 17;
                                                break;
                                }
                                switch (becaEstudiante.getSelectedIndex()) {
                                        case 0:
                                                beca = true;
                                                break;
                                        case 1:
                                                beca = false;
                                                break;
                                }
                                switch (estadoEstudiante.getSelectedIndex()) {
                                        case 0:
                                                estado = true;
                                                break;
                                        case 1:
                                                estado = false;
                                                break;
                                }
                                archivo.clearFile();
                                for (Persona persona : lista) {
                                        if ((persona.getCedula().equals(usuarioEncontrado.getPersona().getCedula()))
                                                        && (persona instanceof Estudiante)) {
                                                Estudiante estudiante = (Estudiante) persona;
                                                estudiante.setActividad(estado);
                                                estudiante.setApellido(apellidosEstudiante.getText());
                                                estudiante.setBeca(beca);
                                                estudiante.setCedula(cedulaEstudiante.getText());
                                                estudiante.setEdad(edad);
                                                estudiante.setGrupo(Integer.parseInt(seccionEstudiante.getText()));
                                                estudiante.setNombre(nombreEstudiante.getText());
                                                JOptionPane.showMessageDialog(rootPane, "Estudiante editado con exito.",
                                                                "Registro", 1);
                                                for (Persona i : lista) {
                                                        archivo.EscribirEnArchivo(i);
                                                }
                                                break;
                                        }
                                }
                                dispose();
                        } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(rootPane, "Ingrese un numero para seccion.", "Error", 0);
                        }
                }
        }// GEN-LAST:event_editarBtnActionPerformed

        public boolean revisarEstudiante() {
                this.lista = archivo.LeerDatosDeArchivo();
                Estudiante estudiante = (Estudiante) usuarioEncontrado.getPersona();
                for (Persona persona : lista) {
                        if (cedulaEstudiante.getText().equals(estudiante.getCedula())) {
                                return false;
                        } else if ((cedulaEstudiante.getText().equals(persona.getCedula()))) {
                                JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con dichos datos.",
                                                "Error", 0);
                                return true;
                        } else if ((nombreEstudiante.getText().equals("")) || (apellidosEstudiante.getText().equals(""))
                                        || (cedulaEstudiante.getText().equals(""))
                                        || (seccionEstudiante.getText().equals(""))) {
                                JOptionPane.showMessageDialog(rootPane, "Campos vacios.", "Error", 0);
                                return true;
                        }
                }

                return false;
        }

        private void becaEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_becaEstudianteActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_becaEstudianteActionPerformed

        private void estadoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoEstudianteActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_estadoEstudianteActionPerformed

        private void edadEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_edadEstudianteActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_edadEstudianteActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField apellidosEstudiante;
        private javax.swing.JComboBox<String> becaEstudiante;
        private javax.swing.JTextField cedulaEstudiante;
        private javax.swing.JComboBox<String> edadEstudiante;
        private com.k33ptoo.components.KButton editarBtn;
        private javax.swing.JComboBox<String> estadoEstudiante;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTextField nombreEstudiante;
        private javax.swing.JTextField seccionEstudiante;
        private com.k33ptoo.components.KButton volver;
        // End of variables declaration//GEN-END:variables
}
