/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloRegistro;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import Archivos.ManejoDeArchivos;
import Persona.Cocinero;
import Persona.Persona;

public class editarCocinero extends javax.swing.JFrame {

    public ManejoDeArchivos archivo;
    public ArrayList<Persona> lista;

    public editarCocinero() {
        initComponents();
        this.archivo = new ManejoDeArchivos();
        this.lista = archivo.LeerDatosDeArchivo();
        Cocinero cocinero = (Cocinero) usuarioEncontrado.getPersona();
        nombreCocinero.setText(cocinero.getNombre());
        apellidosCocinero.setText(cocinero.getApellido());
        cedulaCocinero.setText(cocinero.getCedula());
        salarioCocinero.setText(cocinero.getSalario() + "");
        if (cocinero.isActividad()) {
            estadoCocinero.setSelectedIndex(0);
        } else {
            estadoCocinero.setSelectedIndex(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        estadoCocinero = new javax.swing.JComboBox<>();
        nombreCocinero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        apellidosCocinero = new javax.swing.JTextField();
        salarioCocinero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cedulaCocinero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editarBtn = new com.k33ptoo.components.KButton();
        volver = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 121, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Apellidos:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel8.setText("Estado:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        estadoCocinero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoCocinero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel2.add(estadoCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 87, -1));

        nombreCocinero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel2.add(nombreCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 248, -1));

        jLabel7.setText("Nombre:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        apellidosCocinero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel2.add(apellidosCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 250, -1));

        salarioCocinero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel2.add(salarioCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 248, -1));

        jLabel13.setText("Salario:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        jLabel12.setText("Cedula:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        cedulaCocinero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel2.add(cedulaCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Editar ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 6, -1, -1));

        editarBtn.setText("Editar");
        editarBtn.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        editarBtn.setkEndColor(new java.awt.Color(51, 51, 51));
        editarBtn.setkHoverColor(new java.awt.Color(102, 102, 102));
        editarBtn.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        editarBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        editarBtn.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        editarBtn.setkStartColor(new java.awt.Color(51, 51, 51));
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 150, -1));

        volver.setText("Volver");
        volver.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        volver.setkEndColor(new java.awt.Color(102, 102, 102));
        volver.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        volver.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        volver.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        volver.setkStartColor(new java.awt.Color(51, 51, 51));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverActionPerformed
        dispose();
    }// GEN-LAST:event_volverActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarBtnActionPerformed
        if (revisarCocinero()) {
            return;
        } else {
            try {
                boolean estado = false;
                switch (estadoCocinero.getSelectedIndex()) {
                    case 0:
                        estado = true;
                        break;
                    case 1:
                        estado = false;
                        break;
                }
                archivo.clearFile();
                for (Persona persona : lista) {
                    if (persona.getCedula().equals(usuarioEncontrado.getPersona().getCedula())
                            && (persona instanceof Cocinero)) {
                        Cocinero cocinero = (Cocinero) persona;
                        cocinero.setActividad(estado);
                        cocinero.setApellido(apellidosCocinero.getText());
                        cocinero.setCedula(cedulaCocinero.getText());
                        cocinero.setNombre(nombreCocinero.getText());
                        cocinero.setSalario(Double.parseDouble(salarioCocinero.getText()));
                        JOptionPane.showMessageDialog(rootPane, "Cocinero editado con exito.", "Registro", 1);
                        for (Persona i : lista) {
                            archivo.EscribirEnArchivo(i);
                        }
                        break;
                    }
                }
                dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese numero para salario.", "Error", 0);
            }
        }
    }// GEN-LAST:event_editarBtnActionPerformed

    public boolean revisarCocinero() {
        lista = archivo.LeerDatosDeArchivo();
        for (Persona persona : lista) {
            if (cedulaCocinero.getText().equals(persona.getCedula())) {
                JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con esa cedula.", "Error", 0);
                return true;
            } else if ((nombreCocinero.getText().equals("")) || (apellidosCocinero.getText().equals(""))
                    || (cedulaCocinero.getText().equals("")) || (salarioCocinero.getText().equals(""))) {
                JOptionPane.showMessageDialog(rootPane, "Campos vacios.", "Error", 0);
                return false;
            }
        }

        return false;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosCocinero;
    private javax.swing.JTextField cedulaCocinero;
    private com.k33ptoo.components.KButton editarBtn;
    private javax.swing.JComboBox<String> estadoCocinero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreCocinero;
    private javax.swing.JTextField salarioCocinero;
    private com.k33ptoo.components.KButton volver;
    // End of variables declaration//GEN-END:variables
}
