/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.util.Collections;
import java.util.List;

import javax.swing.JOptionPane;

import Archivos.ManejoArchivos;
import Libros.Libro;
import Libros.TituloComp;

/**
 *
 * @author GabrielPC
 */
public class RegistroDevolucion extends javax.swing.JFrame {

    public List<Libro> libros = ManejoArchivos.LeerDatosDeArchivo();

    public RegistroDevolucion() {
        initComponents();
        Collections.sort(libros, new TituloComp());
        for (Libro libro : libros) {
            listaLibros.addItem(libro.getIdentificador()+"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listaLibros = new javax.swing.JComboBox<>();
        devolverBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 153, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(listaLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, -1));

        devolverBtn.setText("Devolver");
        devolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(devolverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        volverBtn.setText("Regresar");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/book.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void devolverBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_devolverBtnActionPerformed
        for (Libro libro : libros) {
            if (libro.getTitulo().equals((String) listaLibros.getSelectedItem())) {
                if (libro.getEjemplares() == libro.getCantidad()) {
                    JOptionPane.showMessageDialog(rootPane, "Maxima cantidad de ejemplares alcanzada.", getTitle(), 0);
                    return;
                } else {
                    libro.setCantidad(libro.getCantidad() + 1);
                    ManejoArchivos archivo = new ManejoArchivos();
                    List<Libro> nuevaLista = libros;
                    archivo.BorrarDatos();
                    for (Libro libro2 : nuevaLista) {
                        archivo.EscribirEnArchivo(libro2);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Libro devuelto.", getTitle(), 1);
                    dispose();
                }
            }
        }
    }// GEN-LAST:event_devolverBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverBtnActionPerformed
        dispose();
    }// GEN-LAST:event_volverBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devolverBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listaLibros;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
