/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Archivos.ManejoArchivos;
import Libros.GeneroComp;
import Libros.Libro;
import Libros.TituloComp;

/**
 *
 * @author GabrielPC
 */
public class RegistroRetiro extends javax.swing.JFrame {

    public List<Libro> libros = ManejoArchivos.LeerDatosDeArchivo();

    public RegistroRetiro() {
        initComponents();
        Collections.sort(libros, new TituloComp());
        for (Libro libro : libros) {
            listaLibros.addItem(libro.getIdentificador()+"");
        }
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("Genero");
        modelo.addColumn("Ejemplares");
        Collections.sort(libros, new GeneroComp());
        for (Libro libro : libros) {
            modelo.addRow(new Object[] {
                    libro.getIdentificador(), libro.getTitulo(), libro.getAutor(), libro.getGenero(),
                    libro.getCantidad()
            });
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listaLibros = new javax.swing.JComboBox<>();
        retirarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 153, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(listaLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, -1));

        retirarBtn.setText("Retirar");
        retirarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(retirarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        volverBtn.setText("Regresar");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menus/book.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 310, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverBtnActionPerformed
        dispose();
    }// GEN-LAST:event_volverBtnActionPerformed

    private void retirarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_retirarBtnActionPerformed
        for (Libro libro : libros) {
            if (libro.getTitulo().equals((String) listaLibros.getSelectedItem())) {
                if (libro.getCantidad() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Ya no hay ejemplares del libro seleccionado.", getTitle(), 0);
                    return;
                } else {
                    libro.setCantidad(libro.getCantidad() - 1);
                    ManejoArchivos archivo = new ManejoArchivos();
                    List <Libro> nuevaLista = libros;
                    archivo.BorrarDatos();
                    for (Libro libro2 : nuevaLista) {
                        archivo.EscribirEnArchivo(libro2);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Libro retirado.", getTitle(), 1);
                    dispose();
                }
            }
        }

    }// GEN-LAST:event_retirarBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> listaLibros;
    private javax.swing.JButton retirarBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
