/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.util.List;

import javax.swing.JOptionPane;

import Archivos.ManejoArchivos;
import Automovil.Automovil;

public class CalculoMenu extends javax.swing.JFrame {

    public ManejoArchivos archivo;
    public List<Automovil> carros;

    public CalculoMenu() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.archivo = new ManejoArchivos();
        this.carros = archivo.LeerDatosDeArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        calculoTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kmTxt = new javax.swing.JTextField();
        volverBtn1 = new javax.swing.JButton();
        calculoBtn = new javax.swing.JButton();
        placaTxt1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/vehicle.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        calculoTxt.setEditable(false);
        jPanel1.add(calculoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 300, -1));

        jLabel7.setText("Placa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel1.add(kmTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        volverBtn1.setText("Volver");
        volverBtn1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 0)));
        volverBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, 30));

        calculoBtn.setText("Buscar y Calcular");
        calculoBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 0)));
        calculoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(calculoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, 30));
        jPanel1.add(placaTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 207, -1));

        jLabel8.setText("Km:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtn1ActionPerformed
        new MenuPrincipal();
        dispose();
    }//GEN-LAST:event_volverBtn1ActionPerformed

    private void calculoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculoBtnActionPerformed
        Automovil carro = revisarCarro();
        if (carro == null) {
            return;
        } else {
            calculoTxt.setText("Tiempo estimado en recorrer " + kmTxt.getText() + "kms: " + carro.calculaTiempo(Integer.parseInt(kmTxt.getText())) + " horas");
        }
    }//GEN-LAST:event_calculoBtnActionPerformed

    public Automovil revisarCarro() {
        for (Automovil automovil : carros) {
            if (automovil.getPlaca().equals(placaTxt1.getText())) {
                return automovil;
            } else if (kmTxt.getText().equals("") || placaTxt1.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campos vacios.", getTitle(), 0);
                return null;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Carro no encontrado.", getTitle(), 0);
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculoBtn;
    private javax.swing.JTextField calculoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kmTxt;
    private javax.swing.JTextField placaTxt1;
    private javax.swing.JButton volverBtn1;
    // End of variables declaration//GEN-END:variables
}
