/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.util.List;

import javax.swing.JOptionPane;

import Archivos.ManejoArchivos;
import Automovil.Automovil;

/**
 *
 * @author gabos
 */
public class RegistroCarro extends javax.swing.JFrame {

    public ManejoArchivos archivo;
    public List<Automovil> carros;

    public RegistroCarro() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.archivo = new ManejoArchivos();
        this.carros = archivo.LeerDatosDeArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vmaxTxt = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registroCarro = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        combustibleBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        transBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        placaTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        colorTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(vmaxTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, -1));
        jPanel1.add(marcaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 207, -1));
        jPanel1.add(modeloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 207, -1));

        jLabel1.setText("Combustible:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel2.setText("Velocidad MAX:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        jLabel3.setText("Marca:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("Modelo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/vehicle.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        registroCarro.setText("Registrar carro");
        registroCarro
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 0)));
        registroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroCarroActionPerformed(evt);
            }
        });
        jPanel1.add(registroCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 110, 30));

        volverBtn.setText("Volver");
        volverBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 0)));
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 70, 30));

        combustibleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Gasolina" }));
        jPanel1.add(combustibleBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, -1));

        jLabel6.setText("Transmision:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        transBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatico" }));
        jPanel1.add(transBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 120, -1));

        jLabel7.setText("Placa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel1.add(placaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 207, -1));

        jLabel8.setText("Color:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel1.add(colorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroCarroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registroCarroActionPerformed
        if (revisarCarro()) {
            return;
        } else {
            Automovil carro = new Automovil(marcaTxt.getText(), combustibleBox.getSelectedItem().toString(),
                    transBox.getSelectedItem().toString(), colorTxt.getText(),
                    Integer.parseInt(modeloTxt.getText()), Integer.parseInt(vmaxTxt.getText()), placaTxt.getText());
            archivo.EscribirEnArchivo(carro);
            carros = archivo.LeerDatosDeArchivo();
            marcaTxt.setText("");
            colorTxt.setText("");
            modeloTxt.setText("");
            vmaxTxt.setText("");
            placaTxt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Carro registrado exitosamente.", getTitle(), 1);
        }
    }// GEN-LAST:event_registroCarroActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverBtnActionPerformed
        new MenuPrincipal();
        dispose();
    }// GEN-LAST:event_volverBtnActionPerformed

    public boolean revisarCarro() {
        for (Automovil automovil : carros) {
            if (automovil.getPlaca().equals(placaTxt.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Carro ya existe.", getTitle(), 0);
                marcaTxt.setText("");
                colorTxt.setText("");
                modeloTxt.setText("");
                vmaxTxt.setText("");
                placaTxt.setText("");
                return true;
            } else if (placaTxt.getText().equals("") || marcaTxt.getText().equals("") || modeloTxt.getText().equals("")
                    || colorTxt.getText().equals("") || vmaxTxt.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campos vacios.", getTitle(), 0);
                return true;
            }
        }

        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField colorTxt;
    private javax.swing.JComboBox<String> combustibleBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JTextField placaTxt;
    private javax.swing.JButton registroCarro;
    private javax.swing.JComboBox<String> transBox;
    private javax.swing.JTextField vmaxTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
