/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registro;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import Archivos.ManejoDeArchivos;
import Persona.Estudiante;
import Persona.Persona;

/**
 *
 * @author GabrielPC
 */
public class editarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form editarEstudiante
     */
    public editarEstudiante() {
        initComponents();
        Estudiante estudiante = (Estudiante) usuarioEncontrado.getPersona();
        nombreEstudiante.setText(estudiante.getNombre());
        apellidosEstudiante.setText(estudiante.getApellido());
        cedulaEstudiante.setText(estudiante.getCedula());
        seccionEstudiante.setText(estudiante.getGrupo() + "");
        if (estudiante.isBeca()) {
            becaEstudiante.setSelectedIndex(0);
        } else {
            becaEstudiante.setSelectedIndex(1);
        }
        if (estudiante.isActividad()) {
            estadoEstudiante.setSelectedIndex(0);
        } else {
            estadoEstudiante.setSelectedIndex(1);
        }
        switch (estudiante.getEdad()) {
            case 13:
                edadEstudiante.setSelectedIndex(0);
                break;
            case 14:
                edadEstudiante.setSelectedIndex(1);
                break;
            case 15:
                edadEstudiante.setSelectedIndex(2);
                break;
            case 16:
                edadEstudiante.setSelectedIndex(3);
                break;
            case 17:
                edadEstudiante.setSelectedIndex(4);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        becaEstudiante = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        seccionEstudiante = new javax.swing.JTextField();
        nombreEstudiante = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cedulaEstudiante = new javax.swing.JTextField();
        apellidosEstudiante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        estadoEstudiante = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        edadEstudiante = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        editarEstudiante = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        volverEstudiante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        becaEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        becaEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        becaEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becaEstudianteActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellidos:");

        jLabel2.setText("Edad:");

        jLabel1.setText("Nombre:");

        seccionEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, null, new java.awt.Color(102, 102, 102)));

        nombreEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, null, new java.awt.Color(153, 153, 153)));

        jLabel9.setText("Seccion:");

        cedulaEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null,
                null, null, new java.awt.Color(102, 102, 102)));

        apellidosEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED,
                null, null, null, new java.awt.Color(153, 153, 153)));

        jLabel6.setText("Cedula:");

        estadoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estadoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoEstudianteActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");

        edadEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13", "14", "15", "16", "17" }));
        edadEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edadEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadEstudianteActionPerformed(evt);
            }
        });

        jLabel4.setText("Beca:");

        editarEstudiante.setText("Editar");
        editarEstudiante.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
                null, new java.awt.Color(51, 51, 51)));
        editarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEstudianteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Editar ");

        volverEstudiante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        volverEstudiante.setText("Volver");
        volverEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(57, 57, 57)
                                                                .addComponent(cedulaEstudiante,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 279,
                                                                        Short.MAX_VALUE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(50, 50, 50)
                                                                .addComponent(nombreEstudiante,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 279,
                                                                        Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jLabel2))
                                                                        .addGap(45, 45, 45)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(edadEstudiante,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                60,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addComponent(apellidosEstudiante)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel5))
                                                                        .addGap(53, 53, 53)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(seccionEstudiante)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createSequentialGroup()
                                                                                        .addGroup(jPanel2Layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(
                                                                                                        estadoEstudiante,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        96,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(
                                                                                                        becaEstudiante,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        96,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGap(0, 183,
                                                                                                Short.MAX_VALUE))))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(168, 168, 168)
                                                                .addComponent(jLabel7))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(156, 156, 156)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.CENTER)
                                                                        .addComponent(editarEstudiante,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                99,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(volverEstudiante))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(apellidosEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(edadEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(cedulaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(seccionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(becaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(estadoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(volverEstudiante)
                                .addGap(5, 5, 5)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void becaEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_becaEstudianteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_becaEstudianteActionPerformed

    private void estadoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoEstudianteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_estadoEstudianteActionPerformed

    private void edadEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_edadEstudianteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_edadEstudianteActionPerformed

    private void editarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarEstudianteActionPerformed
        ArrayList<Persona> personas = new ManejoDeArchivos().LeerDatosDeArchivo();
        ManejoDeArchivos archivo = new ManejoDeArchivos();
        String nombre = nombreEstudiante.getText(), apellido = apellidosEstudiante.getText(),
                cedula = cedulaEstudiante.getText();
        int edad = 0, seccion = Integer.parseInt(seccionEstudiante.getText());
        boolean beca = false, estado = false;
        switch (edadEstudiante.getSelectedIndex()) {
            case 0:
                edad = 13;
                break;
            case 1:
                edad = 14;
                break;
            case 2:
                edad = 15;
                break;
            case 3:
                edad = 16;
                break;
            case 4:
                edad = 17;
                break;
        }
        switch (becaEstudiante.getSelectedIndex()) {
            case 0:
                beca = true;
                break;
            case 1:
                beca = false;
                break;
        }
        switch (estadoEstudiante.getSelectedIndex()) {
            case 0:
                estado = true;
                break;
            case 1:
                estado = false;
                break;
        }
        archivo.clearFile();
        for (Persona persona : personas) {
            if ((persona.getCedula().equals(usuarioEncontrado.getPersona().getCedula()))
                    && (persona instanceof Estudiante)) {
                Estudiante estudiante = (Estudiante) persona;
                estudiante.setActividad(estado);
                estudiante.setApellido(apellido);
                estudiante.setBeca(beca);
                estudiante.setCedula(cedula);
                estudiante.setEdad(edad);
                estudiante.setGrupo(seccion);
                estudiante.setNombre(nombre);
                JOptionPane.showMessageDialog(rootPane, "Estudiante editado con exito.", "Registro", 1);
                for (Persona i : personas) {
                    archivo.EscribirEnArchivo(i);
                }
                break;
            }
        }
        dispose();

    }// GEN-LAST:event_editarEstudianteActionPerformed

    private void volverEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverEstudianteActionPerformed
        dispose();
    }// GEN-LAST:event_volverEstudianteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosEstudiante;
    private javax.swing.JComboBox<String> becaEstudiante;
    private javax.swing.JTextField cedulaEstudiante;
    private javax.swing.JComboBox<String> edadEstudiante;
    private javax.swing.JButton editarEstudiante;
    private javax.swing.JComboBox<String> estadoEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreEstudiante;
    private javax.swing.JTextField seccionEstudiante;
    private javax.swing.JButton volverEstudiante;
    // End of variables declaration//GEN-END:variables
}
