/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registro;

import java.util.List;
import javax.swing.JOptionPane;
import Archivos.ManejoDeArchivos;
import Menu.MenuPrincipal;
import Persona.*;
import java.awt.*;

public class ModuloRegistro extends javax.swing.JFrame {

    /**
     * Creates new form ModuloRegistro
     */
    CardLayout cardLayout;

    public ModuloRegistro() {
        initComponents();
        cardLayout = (CardLayout) (pnlCards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        customLayout = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        moduloEstudiante = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        pnlEstudiante = new keeptoo.KGradientPanel();
        nombreEstudiante = new javax.swing.JTextField();
        apellidosEstudiante = new javax.swing.JTextField();
        cedulaEstudiante = new javax.swing.JTextField();
        seccionEstudiante = new javax.swing.JTextField();
        becaEstudiante = new javax.swing.JComboBox<>();
        edadEstudiante = new javax.swing.JComboBox<>();
        estadoEstudiante = new javax.swing.JComboBox<>();
        crearEstudiante = new com.k33ptoo.components.KButton();
        volverEstudiante = new com.k33ptoo.components.KButton();
        pnlProfesor = new keeptoo.KGradientPanel();
        nombreProfesor = new javax.swing.JTextField();
        apellidosProfesor = new javax.swing.JTextField();
        correoProfesor = new javax.swing.JTextField();
        cedulaProfesor = new javax.swing.JTextField();
        estadoProfesor = new javax.swing.JComboBox<>();
        salarioProfesor = new javax.swing.JTextField();
        crearProfesor = new com.k33ptoo.components.KButton();
        volverProfesor = new com.k33ptoo.components.KButton();
        pnlCocinero = new keeptoo.KGradientPanel();
        cedulaCocinero = new javax.swing.JTextField();
        nombreCocinero = new javax.swing.JTextField();
        apellidosCocinero = new javax.swing.JTextField();
        salarioCocinero = new javax.swing.JTextField();
        estadoCocinero = new javax.swing.JComboBox<>();
        crearCocinero = new com.k33ptoo.components.KButton();
        volverCocinero = new com.k33ptoo.components.KButton();
        pnlAdmin = new keeptoo.KGradientPanel();
        pnlBuscar = new keeptoo.KGradientPanel();
        cedulaBuscar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        buscarPersona = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 652, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 401, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        moduloEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        moduloEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        moduloEstudiante.setText("Estudiante");
        moduloEstudiante.setBorder(null);
        moduloEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloEstudianteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Profesor");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Cocinero");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Admin");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Buscar");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(moduloEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(48, Short.MAX_VALUE)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(moduloEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addGap(18, 18, 18)));

        jSplitPane1.setLeftComponent(jPanel6);

        pnlCards.setLayout(new java.awt.CardLayout());

        pnlEstudiante.setkEndColor(new java.awt.Color(255, 255, 255));
        pnlEstudiante.setkStartColor(new java.awt.Color(153, 153, 153));
        pnlEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        nombreEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        nombreEstudiante.setText("Nombre...");
        nombreEstudiante
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        nombreEstudiante.setCaretColor(new java.awt.Color(0, 0, 255));
        nombreEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreEstudianteMouseClicked(evt);
            }
        });
        nombreEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(nombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 321, -1));

        apellidosEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        apellidosEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        apellidosEstudiante.setText("Apellidos..");
        apellidosEstudiante
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        apellidosEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apellidosEstudianteMouseClicked(evt);
            }
        });
        pnlEstudiante.add(apellidosEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 321, -1));

        cedulaEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        cedulaEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        cedulaEstudiante.setText("Cedula...");
        cedulaEstudiante
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        cedulaEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedulaEstudianteMouseClicked(evt);
            }
        });
        pnlEstudiante.add(cedulaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 321, -1));

        seccionEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        seccionEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        seccionEstudiante.setText("Seccion...");
        seccionEstudiante
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        seccionEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionEstudianteMouseClicked(evt);
            }
        });
        pnlEstudiante.add(seccionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 321, -1));

        becaEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        becaEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        becaEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        becaEstudiante
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        becaEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        becaEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becaEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(becaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 96, -1));

        edadEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        edadEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        edadEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13", "14", "15", "16", "17" }));
        edadEstudiante
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        edadEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edadEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(edadEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 60, -1));

        estadoEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        estadoEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        estadoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoEstudiante
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        estadoEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estadoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(estadoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 96, -1));

        crearEstudiante.setText("Crear");
        crearEstudiante.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        crearEstudiante.setkEndColor(new java.awt.Color(51, 51, 51));
        crearEstudiante.setkHoverColor(new java.awt.Color(102, 102, 102));
        crearEstudiante.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        crearEstudiante.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        crearEstudiante.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        crearEstudiante.setkStartColor(new java.awt.Color(51, 51, 51));
        crearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(crearEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 150, -1));

        volverEstudiante.setText("Volver");
        volverEstudiante.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        volverEstudiante.setkEndColor(new java.awt.Color(102, 102, 102));
        volverEstudiante.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        volverEstudiante.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        volverEstudiante.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        volverEstudiante.setkStartColor(new java.awt.Color(51, 51, 51));
        volverEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(volverEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 80, 30));

        pnlCards.add(pnlEstudiante, "pnlEstudiante");

        pnlProfesor.setkEndColor(new java.awt.Color(255, 255, 255));
        pnlProfesor.setkStartColor(new java.awt.Color(153, 153, 153));
        pnlProfesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreProfesor.setBackground(new java.awt.Color(255, 255, 255));
        nombreProfesor.setForeground(new java.awt.Color(102, 102, 102));
        nombreProfesor.setText("Nombre...");
        nombreProfesor
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        nombreProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreProfesorMouseClicked(evt);
            }
        });
        pnlProfesor.add(nombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 321, -1));

        apellidosProfesor.setBackground(new java.awt.Color(255, 255, 255));
        apellidosProfesor.setForeground(new java.awt.Color(102, 102, 102));
        apellidosProfesor.setText("Apellidos...");
        apellidosProfesor
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        apellidosProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apellidosProfesorMouseClicked(evt);
            }
        });
        pnlProfesor.add(apellidosProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 321, -1));

        correoProfesor.setBackground(new java.awt.Color(255, 255, 255));
        correoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        correoProfesor.setText("Correo...");
        correoProfesor
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        correoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoProfesorMouseClicked(evt);
            }
        });
        pnlProfesor.add(correoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 320, -1));

        cedulaProfesor.setBackground(new java.awt.Color(255, 255, 255));
        cedulaProfesor.setForeground(new java.awt.Color(102, 102, 102));
        cedulaProfesor.setText("Cedula...");
        cedulaProfesor
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        cedulaProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedulaProfesorMouseClicked(evt);
            }
        });
        pnlProfesor.add(cedulaProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 321, -1));

        estadoProfesor.setBackground(new java.awt.Color(255, 255, 255));
        estadoProfesor.setForeground(new java.awt.Color(0, 0, 0));
        estadoProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoProfesor
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        estadoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoProfesorActionPerformed(evt);
            }
        });
        pnlProfesor.add(estadoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 87, -1));

        salarioProfesor.setBackground(new java.awt.Color(255, 255, 255));
        salarioProfesor.setForeground(new java.awt.Color(102, 102, 102));
        salarioProfesor.setText("Salario...");
        salarioProfesor
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        salarioProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salarioProfesorMouseClicked(evt);
            }
        });
        salarioProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioProfesorActionPerformed(evt);
            }
        });
        pnlProfesor.add(salarioProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 321, -1));

        crearProfesor.setText("Crear");
        crearProfesor.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        crearProfesor.setkEndColor(new java.awt.Color(51, 51, 51));
        crearProfesor.setkHoverColor(new java.awt.Color(102, 102, 102));
        crearProfesor.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        crearProfesor.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        crearProfesor.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        crearProfesor.setkStartColor(new java.awt.Color(51, 51, 51));
        crearProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProfesorActionPerformed(evt);
            }
        });
        pnlProfesor.add(crearProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 150, -1));

        volverProfesor.setText("Volver");
        volverProfesor.setToolTipText("");
        volverProfesor.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        volverProfesor.setkEndColor(new java.awt.Color(102, 102, 102));
        volverProfesor.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        volverProfesor.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        volverProfesor.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        volverProfesor.setkStartColor(new java.awt.Color(51, 51, 51));
        volverProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverProfesorActionPerformed(evt);
            }
        });
        pnlProfesor.add(volverProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 80, 30));

        pnlCards.add(pnlProfesor, "pnlProfesor");

        pnlCocinero.setkEndColor(new java.awt.Color(255, 255, 255));
        pnlCocinero.setkStartColor(new java.awt.Color(153, 153, 153));
        pnlCocinero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cedulaCocinero.setBackground(new java.awt.Color(255, 255, 255));
        cedulaCocinero.setForeground(new java.awt.Color(102, 102, 102));
        cedulaCocinero.setText("Cedula...");
        cedulaCocinero
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        cedulaCocinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedulaCocineroMouseClicked(evt);
            }
        });
        pnlCocinero.add(cedulaCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 321, -1));

        nombreCocinero.setBackground(new java.awt.Color(255, 255, 255));
        nombreCocinero.setForeground(new java.awt.Color(102, 102, 102));
        nombreCocinero.setText("Nombre...");
        nombreCocinero
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        nombreCocinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreCocineroMouseClicked(evt);
            }
        });
        pnlCocinero.add(nombreCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 321, -1));

        apellidosCocinero.setBackground(new java.awt.Color(255, 255, 255));
        apellidosCocinero.setForeground(new java.awt.Color(102, 102, 102));
        apellidosCocinero.setText("Apellidos...");
        apellidosCocinero
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        apellidosCocinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apellidosCocineroMouseClicked(evt);
            }
        });
        pnlCocinero.add(apellidosCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 321, -1));

        salarioCocinero.setBackground(new java.awt.Color(255, 255, 255));
        salarioCocinero.setForeground(new java.awt.Color(102, 102, 102));
        salarioCocinero.setText("Salario...");
        salarioCocinero
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        salarioCocinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salarioCocineroMouseClicked(evt);
            }
        });
        salarioCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioCocineroActionPerformed(evt);
            }
        });
        pnlCocinero.add(salarioCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 321, -1));

        estadoCocinero.setBackground(new java.awt.Color(255, 255, 255));
        estadoCocinero.setForeground(new java.awt.Color(0, 0, 0));
        estadoCocinero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoCocinero
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 102, 102)));
        estadoCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCocineroActionPerformed(evt);
            }
        });
        pnlCocinero.add(estadoCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 102, -1));

        crearCocinero.setText("Crear");
        crearCocinero.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        crearCocinero.setkEndColor(new java.awt.Color(51, 51, 51));
        crearCocinero.setkHoverColor(new java.awt.Color(102, 102, 102));
        crearCocinero.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        crearCocinero.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        crearCocinero.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        crearCocinero.setkStartColor(new java.awt.Color(51, 51, 51));
        crearCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCocineroActionPerformed(evt);
            }
        });
        pnlCocinero.add(crearCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 150, -1));

        volverCocinero.setText("Volver");
        volverCocinero.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        volverCocinero.setkEndColor(new java.awt.Color(102, 102, 102));
        volverCocinero.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        volverCocinero.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        volverCocinero.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        volverCocinero.setkStartColor(new java.awt.Color(51, 51, 51));
        volverCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverCocineroActionPerformed(evt);
            }
        });
        pnlCocinero.add(volverCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 80, 30));

        pnlCards.add(pnlCocinero, "pnlCocinero");

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
                pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 596, Short.MAX_VALUE));
        pnlAdminLayout.setVerticalGroup(
                pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 374, Short.MAX_VALUE));

        pnlCards.add(pnlAdmin, "card3");

        pnlBuscar.setkEndColor(new java.awt.Color(255, 255, 255));
        pnlBuscar.setkStartColor(new java.awt.Color(153, 153, 153));
        pnlBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlBuscar.add(cedulaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 167, 41));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Introduzca la cedula:");
        pnlBuscar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        buscarPersona.setText("Buscar");
        buscarPersona.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        buscarPersona.setkEndColor(new java.awt.Color(51, 51, 51));
        buscarPersona.setkHoverColor(new java.awt.Color(102, 102, 102));
        buscarPersona.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        buscarPersona.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        buscarPersona.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        buscarPersona.setkStartColor(new java.awt.Color(51, 51, 51));
        buscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPersonaActionPerformed(evt);
            }
        });
        pnlBuscar.add(buscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 100, 40));

        kButton2.setText("Volver");
        kButton2.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton2.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton2.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton2.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        pnlBuscar.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 80, 30));

        pnlCards.add(pnlBuscar, "pnlBuscar");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout customLayoutLayout = new javax.swing.GroupLayout(customLayout);
        customLayout.setLayout(customLayoutLayout);
        customLayoutLayout.setHorizontalGroup(
                customLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(customLayoutLayout.createSequentialGroup()
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        customLayoutLayout.setVerticalGroup(
                customLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(customLayoutLayout.createSequentialGroup()
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(customLayout, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(customLayout, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_kButton2ActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
    }// GEN-LAST:event_kButton2ActionPerformed

    private void buscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buscarPersonaActionPerformed
        List<Persona> personas = new ManejoDeArchivos().LeerDatosDeArchivo();
        for (Persona persona : personas) {
            if ((persona instanceof Estudiante) && (cedulaBuscar.getText().equals(persona.getCedula()))) {
                JOptionPane.showMessageDialog(rootPane, "Estudiante encontrado.", "Buscar", 1);
                usuarioEncontrado ventana = new usuarioEncontrado((Estudiante) persona);
                return;
            } else if ((persona instanceof Profesor) && (cedulaBuscar.getText().equals(persona.getCedula()))) {
                JOptionPane.showMessageDialog(rootPane, "Profesor encontrado.", "Buscar", 1);
                usuarioEncontrado ventana = new usuarioEncontrado((Profesor) persona);
                return;
            } else if ((persona instanceof Cocinero) && (cedulaBuscar.getText().equals(persona.getCedula()))) {
                JOptionPane.showMessageDialog(rootPane, "Cocinero encontrado.", "Buscar", 1);
                usuarioEncontrado ventana = new usuarioEncontrado((Cocinero) persona);
                return;
            }
        }
        if (cedulaBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo vacio.", "Error", 0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "El usuario no fue encontrado.", "Error", 0);
        }
    }// GEN-LAST:event_buscarPersonaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        cardLayout.show(pnlCards, "pnlBuscar");
    }// GEN-LAST:event_jButton5ActionPerformed

    private void nombreProfesorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_nombreProfesorMouseClicked
        nombreProfesor.setText("");
        nombreProfesor.setForeground(Color.BLACK);
    }// GEN-LAST:event_nombreProfesorMouseClicked

    private void apellidosProfesorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_apellidosProfesorMouseClicked
        apellidosProfesor.setText("");
        apellidosProfesor.setForeground(Color.BLACK);
    }// GEN-LAST:event_apellidosProfesorMouseClicked

    private void correoProfesorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_correoProfesorMouseClicked
        correoProfesor.setText("");
        correoProfesor.setForeground(Color.BLACK);
    }// GEN-LAST:event_correoProfesorMouseClicked

    private void salarioProfesorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_salarioProfesorMouseClicked
        salarioProfesor.setText("");
        salarioProfesor.setForeground(Color.BLACK);
    }// GEN-LAST:event_salarioProfesorMouseClicked

    private void nombreCocineroMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_nombreCocineroMouseClicked
        nombreCocinero.setText("");
        nombreCocinero.setForeground(Color.BLACK);
    }// GEN-LAST:event_nombreCocineroMouseClicked

    private void apellidosCocineroMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_apellidosCocineroMouseClicked
        apellidosCocinero.setText("");
        apellidosCocinero.setForeground(Color.BLACK);
    }// GEN-LAST:event_apellidosCocineroMouseClicked

    private void cedulaCocineroMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cedulaCocineroMouseClicked
        cedulaCocinero.setText("");
        cedulaCocinero.setForeground(Color.BLACK);
    }// GEN-LAST:event_cedulaCocineroMouseClicked

    private void salarioCocineroMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_salarioCocineroMouseClicked
        salarioCocinero.setText("");
        salarioCocinero.setForeground(Color.BLACK);
    }// GEN-LAST:event_salarioCocineroMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Opcion no disponible.", "Admin", 0);
    }// GEN-LAST:event_jButton4ActionPerformed

    private void cedulaProfesorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cedulaProfesorMouseClicked
        cedulaProfesor.setText("");
        cedulaProfesor.setForeground(Color.BLACK);
    }// GEN-LAST:event_cedulaProfesorMouseClicked

    private void volverEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverEstudianteActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
    }// GEN-LAST:event_volverEstudianteActionPerformed

    private void volverProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverProfesorActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
    }// GEN-LAST:event_volverProfesorActionPerformed

    private void volverCocineroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverCocineroActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
    }// GEN-LAST:event_volverCocineroActionPerformed

    private void crearCocineroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearCocineroActionPerformed
        try {
            String nombre = nombreCocinero.getText(), apellidos = apellidosCocinero.getText(),
                    cedula = cedulaCocinero.getText();
            double salario = Double.parseDouble(salarioCocinero.getText());
            boolean estado = false;
            switch (estadoCocinero.getSelectedIndex()) {
                case 0:
                    estado = true;
                    break;
                case 1:
                    estado = false;
                    break;
            }

            List<Persona> lista = new ManejoDeArchivos().LeerDatosDeArchivo();
            for (Persona persona : lista) {
                if (cedulaCocinero.getText().equals(persona.getCedula())) {
                    JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con dichos datos.", "Error", 0);
                    nombreCocinero.setText("Nombre...");
                    nombreCocinero.setForeground(Color.GRAY);
                    apellidosCocinero.setText("Apellidos...");
                    apellidosCocinero.setForeground(Color.GRAY);
                    cedulaCocinero.setText("Cedula...");
                    cedulaCocinero.setForeground(Color.GRAY);
                    salarioCocinero.setText("Salario...");
                    salarioCocinero.setForeground(Color.GRAY);
                    return;
                } else if ((nombreCocinero.getText().equals("")) || (apellidosCocinero.getText().equals(""))
                        || (cedulaCocinero.getText().equals("")) || (salarioCocinero.getText().equals(""))) {
                    JOptionPane.showMessageDialog(rootPane, "Campos vacios.", "Error", 0);
                    nombreCocinero.setText("Nombre...");
                    nombreCocinero.setForeground(Color.GRAY);
                    apellidosCocinero.setText("Apellidos...");
                    apellidosCocinero.setForeground(Color.GRAY);
                    cedulaCocinero.setText("Cedula...");
                    cedulaCocinero.setForeground(Color.GRAY);
                    salarioCocinero.setText("Salario...");
                    salarioCocinero.setForeground(Color.GRAY);
                    return;
                }
            }
            Persona cocinero = new Cocinero(nombre, apellidos, cedula, estado, salario);
            ManejoDeArchivos archivo = new ManejoDeArchivos();
            archivo.EscribirEnArchivo(cocinero);
            JOptionPane.showMessageDialog(rootPane, "Cocinero creado con exito.", "Registro", 1);
            nombreCocinero.setText("Nombre...");
            nombreCocinero.setForeground(Color.GRAY);
            apellidosCocinero.setText("Apellidos...");
            apellidosCocinero.setForeground(Color.GRAY);
            cedulaCocinero.setText("Cedula...");
            cedulaCocinero.setForeground(Color.GRAY);
            salarioCocinero.setText("Salario...");
            salarioCocinero.setForeground(Color.GRAY);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", 0);
        }
    }// GEN-LAST:event_crearCocineroActionPerformed

    private void crearProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearProfesorActionPerformed
        try {
            String nombre = nombreProfesor.getText(), apellidos = apellidosProfesor.getText(),
                    cedula = cedulaProfesor.getText(), correo = correoProfesor.getText();
            double salario = Double.parseDouble(salarioProfesor.getText());
            boolean estado = false;
            switch (estadoProfesor.getSelectedIndex()) {
                case 0:
                    estado = true;
                    break;
                case 1:
                    estado = false;
                    break;
            }

            List<Persona> lista = new ManejoDeArchivos().LeerDatosDeArchivo();
            for (Persona persona : lista) {
                if (cedulaProfesor.getText().equals(persona.getCedula())) {
                    JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con dichos datos.", "Error", 0);
                    nombreProfesor.setText("Nombre...");
                    nombreProfesor.setForeground(Color.GRAY);
                    apellidosProfesor.setText("Apellidos...");
                    apellidosProfesor.setForeground(Color.GRAY);
                    cedulaProfesor.setText("Cedula...");
                    cedulaProfesor.setForeground(Color.GRAY);
                    correoProfesor.setText("Correo...");
                    correoProfesor.setForeground(Color.GRAY);
                    salarioProfesor.setText("Salario...");
                    salarioProfesor.setForeground(Color.GRAY);
                    return;
                }
            }
            Persona profesor = new Profesor(nombre, apellidos, cedula, estado, correo, salario);
            ManejoDeArchivos archivo = new ManejoDeArchivos();
            archivo.EscribirEnArchivo(profesor);
            nombreProfesor.setText("Nombre...");
            nombreProfesor.setForeground(Color.GRAY);
            apellidosProfesor.setText("Apellidos...");
            apellidosProfesor.setForeground(Color.GRAY);
            cedulaProfesor.setText("Cedula...");
            cedulaProfesor.setForeground(Color.GRAY);
            correoProfesor.setText("Correo...");
            correoProfesor.setForeground(Color.GRAY);
            salarioProfesor.setText("Salario...");
            salarioProfesor.setForeground(Color.GRAY);
            JOptionPane.showMessageDialog(rootPane, "Profesor creado con exito.", "Registro", 1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", 0);
        }
    }// GEN-LAST:event_crearProfesorActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_kButton1ActionPerformed

    private void nombreEstudianteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_nombreEstudianteMouseClicked
        nombreEstudiante.setText("");
        nombreEstudiante.setForeground(Color.BLACK);
    }// GEN-LAST:event_nombreEstudianteMouseClicked

    private void apellidosEstudianteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_apellidosEstudianteMouseClicked
        apellidosEstudiante.setText("");
        apellidosEstudiante.setForeground(Color.BLACK);
    }// GEN-LAST:event_apellidosEstudianteMouseClicked

    private void cedulaEstudianteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cedulaEstudianteMouseClicked
        cedulaEstudiante.setText("");
        cedulaEstudiante.setForeground(Color.BLACK);
    }// GEN-LAST:event_cedulaEstudianteMouseClicked

    private void seccionEstudianteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_seccionEstudianteMouseClicked
        seccionEstudiante.setText("");
        seccionEstudiante.setForeground(Color.BLACK);
    }// GEN-LAST:event_seccionEstudianteMouseClicked

    private void moduloEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_moduloEstudianteActionPerformed
        cardLayout.show(pnlCards, "pnlEstudiante");
    }// GEN-LAST:event_moduloEstudianteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        cardLayout.show(pnlCards, "pnlProfesor");
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        cardLayout.show(pnlCards, "pnlCocinero");
    }// GEN-LAST:event_jButton3ActionPerformed

    private void nombreEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombreEstudianteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nombreEstudianteActionPerformed

    private void crearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearEstudianteActionPerformed
        try {
            String nombre = nombreEstudiante.getText(), apellido = apellidosEstudiante.getText(),
                    cedula = cedulaEstudiante.getText();
            int edad = 0, seccion = Integer.parseInt(seccionEstudiante.getText());
            boolean beca = false, estado = false;
            switch (edadEstudiante.getSelectedIndex()) {
                case 0:
                    edad = 13;
                    break;
                case 1:
                    edad = 14;
                    break;
                case 2:
                    edad = 15;
                    break;
                case 3:
                    edad = 16;
                    break;
                case 4:
                    edad = 17;
                    break;
            }
            switch (becaEstudiante.getSelectedIndex()) {
                case 0:
                    beca = true;
                    break;
                case 1:
                    beca = false;
                    break;
            }
            switch (estadoEstudiante.getSelectedIndex()) {
                case 0:
                    estado = true;
                    break;
                case 1:
                    estado = false;
                    break;
            }
            List<Persona> lista = new ManejoDeArchivos().LeerDatosDeArchivo();
            ManejoDeArchivos archivo = new ManejoDeArchivos();
            for (Persona persona : lista) {
                if ((cedulaEstudiante.getText().equals(persona.getCedula()))) {
                    JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con dichos datos.", "Error", 0);
                    nombreEstudiante.setText("Nombre...");
                    nombreEstudiante.setForeground(Color.GRAY);
                    apellidosEstudiante.setText("Apellidos...");
                    apellidosEstudiante.setForeground(Color.GRAY);
                    cedulaEstudiante.setText("Cedula...");
                    cedulaEstudiante.setForeground(Color.GRAY);
                    seccionEstudiante.setText("Seccion...");
                    seccionEstudiante.setForeground(Color.GRAY);
                    return;
                }
            }
            Persona estudiante = new Estudiante(nombre, apellido, cedula, estado, beca, seccion, edad);
            archivo.EscribirEnArchivo(estudiante);
            nombreEstudiante.setText("Nombre...");
            nombreEstudiante.setForeground(Color.GRAY);
            apellidosEstudiante.setText("Apellidos...");
            apellidosEstudiante.setForeground(Color.GRAY);
            cedulaEstudiante.setText("Cedula...");
            cedulaEstudiante.setForeground(Color.GRAY);
            seccionEstudiante.setText("Seccion...");
            seccionEstudiante.setForeground(Color.GRAY);
            JOptionPane.showMessageDialog(rootPane, "Estudiante creado con exito.", "Registro", 1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", 0);
        }
    }// GEN-LAST:event_crearEstudianteActionPerformed

    private void salarioProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salarioProfesorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_salarioProfesorActionPerformed

    private void volverBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverBuscarActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
    }// GEN-LAST:event_volverBuscarActionPerformed

    private void estadoCocineroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoCocineroActionPerformed

    }// GEN-LAST:event_estadoCocineroActionPerformed

    private void salarioCocineroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoCocineroActionPerformed

    }// GEN-LAST:event_estadoCocineroActionPerformed

    private void becaEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_becaEstudianteActionPerformed

    }// GEN-LAST:event_becaEstudianteActionPerformed

    private void edadEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_edadEstudianteActionPerformed

    }// GEN-LAST:event_edadEstudianteActionPerformed

    private void estadoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoEstudianteActionPerformed

    }// GEN-LAST:event_estadoEstudianteActionPerformed

    private void estadoProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salarioProfesorActionPerformed

    }// GEN-LAST:event_salarioProfesorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosCocinero;
    private javax.swing.JTextField apellidosEstudiante;
    private javax.swing.JTextField apellidosProfesor;
    private javax.swing.JComboBox<String> becaEstudiante;
    private com.k33ptoo.components.KButton buscarPersona;
    private javax.swing.JTextField cedulaBuscar;
    private javax.swing.JTextField cedulaCocinero;
    private javax.swing.JTextField cedulaEstudiante;
    private javax.swing.JTextField cedulaProfesor;
    private javax.swing.JTextField correoProfesor;
    private com.k33ptoo.components.KButton crearCocinero;
    private com.k33ptoo.components.KButton crearEstudiante;
    private com.k33ptoo.components.KButton crearProfesor;
    private javax.swing.JPanel customLayout;
    private javax.swing.JComboBox<String> edadEstudiante;
    private javax.swing.JComboBox<String> estadoCocinero;
    private javax.swing.JComboBox<String> estadoEstudiante;
    private javax.swing.JComboBox<String> estadoProfesor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private com.k33ptoo.components.KButton kButton2;
    private javax.swing.JButton moduloEstudiante;
    private javax.swing.JTextField nombreCocinero;
    private javax.swing.JTextField nombreEstudiante;
    private javax.swing.JTextField nombreProfesor;
    private keeptoo.KGradientPanel pnlAdmin;
    private keeptoo.KGradientPanel pnlBuscar;
    private javax.swing.JPanel pnlCards;
    private keeptoo.KGradientPanel pnlCocinero;
    private keeptoo.KGradientPanel pnlEstudiante;
    private keeptoo.KGradientPanel pnlProfesor;
    private javax.swing.JTextField salarioCocinero;
    private javax.swing.JTextField salarioProfesor;
    private javax.swing.JTextField seccionEstudiante;
    private com.k33ptoo.components.KButton volverCocinero;
    private com.k33ptoo.components.KButton volverEstudiante;
    private com.k33ptoo.components.KButton volverProfesor;
    // End of variables declaration//GEN-END:variables

}
