/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registro;

import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import Archivos.ManejoDeArchivos;
import Menu.MenuPrincipal;
import Persona.*;
import java.awt.*;    
import javax.swing.*;   
import java.awt.event.*;    

/**
 *
 * @author GabrielPC
 */
public class ModuloRegistro extends javax.swing.JFrame {

    /**
     * Creates new form ModuloRegistro
     */
    CardLayout cardLayout;
    public ModuloRegistro() {
        initComponents();
        cardLayout = (CardLayout)(pnlCards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        volverProfesor = new javax.swing.JButton();
        crearProfesor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nombreProfesor = new javax.swing.JTextField();
        estadoProfesor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        correoProfesor = new javax.swing.JTextField();
        cedulaProfesor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        salarioProfesor = new javax.swing.JTextField();
        apellidosProfesor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nombreCocinero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        apellidosCocinero = new javax.swing.JTextField();
        salarioCocinero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        estadoCocinero = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        volverCocinero = new javax.swing.JButton();
        crearCocinero = new javax.swing.JButton();
        cedulaCocinero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        volverBuscar = new javax.swing.JButton();
        buscarUsuario = new javax.swing.JButton();
        cedulaBuscar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        customLayout = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        moduloEstudiante = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        pnlEstudiante = new keeptoo.KGradientPanel();
        nombreEstudiante = new javax.swing.JTextField();
        apellidosEstudiante = new javax.swing.JTextField();
        cedulaEstudiante = new javax.swing.JTextField();
        seccionEstudiante = new javax.swing.JTextField();
        becaEstudiante = new javax.swing.JComboBox<>();
        edadEstudiante = new javax.swing.JComboBox<>();
        estadoEstudiante = new javax.swing.JComboBox<>();
        crearEstudiante = new javax.swing.JButton();
        volverEstudiante = new javax.swing.JButton();
        pnlProfesor = new keeptoo.KGradientPanel();
        pnlCocinero = new keeptoo.KGradientPanel();
        pnlAdmin = new keeptoo.KGradientPanel();
        pnlBuscar = new keeptoo.KGradientPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(0, 204, 204));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        volverProfesor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        volverProfesor.setText("Volver");
        volverProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverProfesorActionPerformed(evt);
            }
        });

        crearProfesor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        crearProfesor.setText("Crear");
        crearProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProfesorActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre:");

        estadoProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoProfesorActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado:");

        jLabel10.setText("Apellidos:");

        jLabel11.setText("Correo:");

        jLabel12.setText("Cedula:");

        jLabel13.setText("Salario:");

        salarioProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(50, 50, 50)
                                .addComponent(nombreProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(45, 45, 45)
                                .addComponent(apellidosProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(58, 58, 58)
                                .addComponent(correoProfesor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(57, 57, 57)
                                .addComponent(cedulaProfesor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(estadoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(salarioProfesor)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(crearProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(volverProfesor)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(apellidosProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(correoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(salarioProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(crearProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(volverProfesor)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Profesor", jPanel1);

        jLabel14.setText("Nombre:");

        salarioCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioCocineroActionPerformed(evt);
            }

            private void salarioCocineroActionPerformed(ActionEvent evt) {
            }
        });

        jLabel15.setText("Estado:");

        estadoCocinero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCocineroActionPerformed(evt);
            }
        });

        jLabel17.setText("Apellidos:");

        jLabel18.setText("Salario:");

        volverCocinero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        volverCocinero.setText("Volver");
        volverCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverCocineroActionPerformed(evt);
            }
        });

        crearCocinero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        crearCocinero.setText("Crear");
        crearCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCocineroActionPerformed(evt);
            }
        });

        jLabel16.setText("Cedula:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crearCocinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverCocinero)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedulaCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombreCocinero)
                        .addComponent(estadoCocinero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salarioCocinero)
                        .addComponent(apellidosCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(apellidosCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(estadoCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverCocinero)
                    .addComponent(crearCocinero))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cocinero", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Admin", jPanel4);

        volverBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        volverBuscar.setText("Volver");
        volverBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBuscarActionPerformed(evt);
            }
        });

        buscarUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buscarUsuario.setText("Buscar");
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });

        jLabel19.setText("Introduzca la cedula:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(volverBuscar)
                    .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverBuscar)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel5);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        moduloEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        moduloEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        moduloEstudiante.setText("Estudiante");
        moduloEstudiante.setBorder(null);
        moduloEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloEstudianteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Profesor");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Cocinero");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Admin");
        jButton4.setBorder(null);

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Buscar");
        jButton5.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moduloEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(moduloEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jSplitPane1.setLeftComponent(jPanel6);

        pnlCards.setLayout(new java.awt.CardLayout());

        pnlEstudiante.setkStartColor(new java.awt.Color(204, 204, 204));
        pnlEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        nombreEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        nombreEstudiante.setText("Nombre");
        nombreEstudiante.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        nombreEstudiante.setCaretColor(new java.awt.Color(0, 0, 255));
        nombreEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(nombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 321, -1));

        apellidosEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        apellidosEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        apellidosEstudiante.setText("Apellidos");
        apellidosEstudiante.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlEstudiante.add(apellidosEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 321, -1));
        pnlEstudiante.add(cedulaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 321, -1));
        pnlEstudiante.add(seccionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 321, -1));

        becaEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        becaEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        becaEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becaEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(becaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 185, 96, -1));

        edadEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13", "14", "15", "16", "17" }));
        edadEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edadEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(edadEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 265, 60, -1));

        estadoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        estadoEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estadoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(estadoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 225, 96, -1));

        crearEstudiante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        crearEstudiante.setText("Crear");
        crearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(crearEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 318, 165, 50));

        volverEstudiante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        volverEstudiante.setText("Volver");
        volverEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverEstudianteActionPerformed(evt);
            }
        });
        pnlEstudiante.add(volverEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 333, -1, -1));

        pnlCards.add(pnlEstudiante, "pnlEstudiante");

        pnlProfesor.setkStartColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlProfesorLayout = new javax.swing.GroupLayout(pnlProfesor);
        pnlProfesor.setLayout(pnlProfesorLayout);
        pnlProfesorLayout.setHorizontalGroup(
            pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        pnlProfesorLayout.setVerticalGroup(
            pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pnlCards.add(pnlProfesor, "pnlProfesor");

        pnlCocinero.setkEndColor(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout pnlCocineroLayout = new javax.swing.GroupLayout(pnlCocinero);
        pnlCocinero.setLayout(pnlCocineroLayout);
        pnlCocineroLayout.setHorizontalGroup(
            pnlCocineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        pnlCocineroLayout.setVerticalGroup(
            pnlCocineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCocinero, "pnlCocinero");

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pnlCards.add(pnlAdmin, "card3");

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pnlCards.add(pnlBuscar, "card2");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout customLayoutLayout = new javax.swing.GroupLayout(customLayout);
        customLayout.setLayout(customLayoutLayout);
        customLayoutLayout.setHorizontalGroup(
            customLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customLayoutLayout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        customLayoutLayout.setVerticalGroup(
            customLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customLayoutLayout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(customLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(customLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moduloEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloEstudianteActionPerformed
        cardLayout.show(pnlCards, "pnlEstudiante");
    }//GEN-LAST:event_moduloEstudianteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cardLayout.show(pnlCards, "pnlProfesor");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nombreEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEstudianteActionPerformed

    private void salarioProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salarioProfesorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_salarioProfesorActionPerformed

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buscarUsuarioActionPerformed

        List<Persona> personas = new ManejoDeArchivos().LeerDatosDeArchivo();
        for (Persona persona : personas) {
            if ((persona instanceof Estudiante) && (cedulaBuscar.getText().equals(persona.getCedula()))) {
                JOptionPane.showMessageDialog(rootPane, "Estudiante encontrado.", "Buscar", 1);
                usuarioEncontrado ventana = new usuarioEncontrado((Estudiante) persona);
                return;
            } else if ((persona instanceof Profesor) && (cedulaBuscar.getText().equals(persona.getCedula()))) {
                JOptionPane.showMessageDialog(rootPane, "Profesor encontrado.", "Buscar", 1);
                usuarioEncontrado ventana = new usuarioEncontrado((Profesor) persona);
                return;
            } else if ((persona instanceof Cocinero) && (cedulaBuscar.getText().equals(persona.getCedula()))) {
                JOptionPane.showMessageDialog(rootPane, "Cocinero encontrado.", "Buscar", 1);
                usuarioEncontrado ventana = new usuarioEncontrado((Cocinero) persona);
                return;
            }
        }
        if (cedulaBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo vacio.", "Error", 0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "El usuario no fue encontrado.", "Error", 0);
        }
    }// GEN-LAST:event_buscarUsuarioActionPerformed

    private void volverBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverBuscarActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
    }// GEN-LAST:event_volverBuscarActionPerformed

    private void estadoCocineroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoCocineroActionPerformed

    }// GEN-LAST:event_estadoCocineroActionPerformed

    private void volverCocineroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverCocineroActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
    }// GEN-LAST:event_volverCocineroActionPerformed

    private void crearCocineroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearCocineroActionPerformed
        String nombre = nombreCocinero.getText(), apellidos = apellidosCocinero.getText(),
                cedula = cedulaCocinero.getText();
        double salario = Double.parseDouble(salarioCocinero.getText());
        boolean estado = false;
        switch (estadoCocinero.getSelectedIndex()) {
            case 0:
                estado = true;
                break;
            case 1:
                estado = false;
                break;
        }

        List<Persona> lista = new ManejoDeArchivos().LeerDatosDeArchivo();
        for (Persona persona : lista) {
            if (cedulaCocinero.getText().equals(persona.getCedula())) {
                JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con dichos datos.", "Error", 0);
                nombreCocinero.setText("");
                apellidosCocinero.setText("");
                cedulaCocinero.setText("");
                salarioCocinero.setText("");
                return;
            }
        }
        Persona cocinero = new Cocinero(nombre, apellidos, cedula, estado, salario);
        ManejoDeArchivos archivo = new ManejoDeArchivos();
        archivo.EscribirEnArchivo(cocinero);
        JOptionPane.showMessageDialog(rootPane, "Cocinero creado con exito.", "Registro", 1);
        nombreCocinero.setText("");
        apellidosCocinero.setText("");
        cedulaCocinero.setText("");
        salarioCocinero.setText("");
    }// GEN-LAST:event_crearCocineroActionPerformed

    private void estadoProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoProfesorActionPerformed

    }// GEN-LAST:event_estadoProfesorActionPerformed

    private void volverProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverEstudianteActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
    }// GEN-LAST:event_volverEstudianteActionPerformed

    private void volverEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverEstudianteActionPerformed
        dispose();
        MenuPrincipal principal = new MenuPrincipal();
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
    }// GEN-LAST:event_volverEstudianteActionPerformed

    private void crearProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearEstudianteActionPerformed
        String nombre = nombreProfesor.getText(), apellidos = apellidosProfesor.getText(),
                cedula = cedulaProfesor.getText(), correo = correoProfesor.getText();
        double salario = Double.parseDouble(salarioProfesor.getText());
        boolean estado = false;
        switch (estadoProfesor.getSelectedIndex()) {
            case 0:
                estado = true;
                break;
            case 1:
                estado = false;
                break;
        }

        List<Persona> lista = new ManejoDeArchivos().LeerDatosDeArchivo();
        for (Persona persona : lista) {
            if (cedulaProfesor.getText().equals(persona.getCedula())) {
                JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con dichos datos.", "Error", 0);
                nombreProfesor.setText("");
                apellidosProfesor.setText("");
                cedulaProfesor.setText("");
                correoProfesor.setText("");
                salarioProfesor.setText("");
                return;
            }
        }
        Persona profesor = new Profesor(nombre, apellidos, cedula, estado, correo, salario);
        ManejoDeArchivos archivo = new ManejoDeArchivos();
        archivo.EscribirEnArchivo(profesor);
        nombreProfesor.setText("");
        correoProfesor.setText("");
        apellidosProfesor.setText("");
        cedulaProfesor.setText("");
        salarioProfesor.setText("");
        JOptionPane.showMessageDialog(rootPane, "Profesor creado con exito.", "Registro", 1);

    }// GEN-LAST:event_crearEstudianteActionPerformed

    private void crearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearEstudianteActionPerformed
        String nombre = nombreEstudiante.getText(), apellido = apellidosEstudiante.getText(),
                cedula = cedulaEstudiante.getText();
        int edad = 0, seccion = Integer.parseInt(seccionEstudiante.getText());
        boolean beca = false, estado = false;
        switch (edadEstudiante.getSelectedIndex()) {
            case 0:
                edad = 13;
                break;
            case 1:
                edad = 14;
                break;
            case 2:
                edad = 15;
                break;
            case 3:
                edad = 16;
                break;
            case 4:
                edad = 17;
                break;
        }
        switch (becaEstudiante.getSelectedIndex()) {
            case 0:
                beca = true;
                break;
            case 1:
                beca = false;
                break;
        }
        switch (estadoEstudiante.getSelectedIndex()) {
            case 0:
                estado = true;
                break;
            case 1:
                estado = false;
                break;
        }
        List<Persona> lista = new ManejoDeArchivos().LeerDatosDeArchivo();
        ManejoDeArchivos archivo = new ManejoDeArchivos();
        for (Persona persona : lista) {
            if ((cedulaEstudiante.getText().equals(persona.getCedula()))) {
                JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con dichos datos.", "Error", 0);
                nombreEstudiante.setText("");
                apellidosEstudiante.setText("");
                cedulaEstudiante.setText("");
                seccionEstudiante.setText("");
                return;
            }
        }
        Persona estudiante = new Estudiante(nombre, apellido, cedula, estado, beca, seccion, edad);
        archivo.EscribirEnArchivo(estudiante);
        nombreEstudiante.setText("");
        apellidosEstudiante.setText("");
        cedulaEstudiante.setText("");
        seccionEstudiante.setText("");
        JOptionPane.showMessageDialog(rootPane, "Estudiante creado con exito.", "Registro", 1);
    }// GEN-LAST:event_crearEstudianteActionPerformed

    private void becaEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_becaEstudianteActionPerformed

    }// GEN-LAST:event_becaEstudianteActionPerformed

    private void edadEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_edadEstudianteActionPerformed

    }// GEN-LAST:event_edadEstudianteActionPerformed

    private void estadoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoEstudianteActionPerformed

    }// GEN-LAST:event_estadoEstudianteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosCocinero;
    private javax.swing.JTextField apellidosEstudiante;
    private javax.swing.JTextField apellidosProfesor;
    private javax.swing.JComboBox<String> becaEstudiante;
    private javax.swing.JButton buscarUsuario;
    private javax.swing.JTextField cedulaBuscar;
    private javax.swing.JTextField cedulaCocinero;
    private javax.swing.JTextField cedulaEstudiante;
    private javax.swing.JTextField cedulaProfesor;
    private javax.swing.JTextField correoProfesor;
    private javax.swing.JButton crearCocinero;
    private javax.swing.JButton crearEstudiante;
    private javax.swing.JButton crearProfesor;
    private javax.swing.JPanel customLayout;
    private javax.swing.JComboBox<String> edadEstudiante;
    private javax.swing.JComboBox<String> estadoCocinero;
    private javax.swing.JComboBox<String> estadoEstudiante;
    private javax.swing.JComboBox<String> estadoProfesor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton moduloEstudiante;
    private javax.swing.JTextField nombreCocinero;
    private javax.swing.JTextField nombreEstudiante;
    private javax.swing.JTextField nombreProfesor;
    private keeptoo.KGradientPanel pnlAdmin;
    private keeptoo.KGradientPanel pnlBuscar;
    private javax.swing.JPanel pnlCards;
    private keeptoo.KGradientPanel pnlCocinero;
    private keeptoo.KGradientPanel pnlEstudiante;
    private keeptoo.KGradientPanel pnlProfesor;
    private javax.swing.JTextField salarioCocinero;
    private javax.swing.JTextField salarioProfesor;
    private javax.swing.JTextField seccionEstudiante;
    private javax.swing.JButton volverBuscar;
    private javax.swing.JButton volverCocinero;
    private javax.swing.JButton volverEstudiante;
    private javax.swing.JButton volverProfesor;
    // End of variables declaration//GEN-END:variables

}
