/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registro;

import javax.swing.table.DefaultTableModel;

import Persona.Cocinero;
import Persona.Estudiante;
import Persona.Persona;
import Persona.Profesor;

public class usuarioEncontrado extends javax.swing.JFrame {

    private int usuario;
    private static Persona persona;

    /**
     * Creates new form usuarioEncontrado
     */
    public usuarioEncontrado(Estudiante estudiante) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Edad");
        modelo.addColumn("Cedula");
        modelo.addColumn("Seccion");
        modelo.addColumn("Beca");
        modelo.addColumn("Estado");
        modelo.addRow(new Object[] { estudiante.getNombre(), estudiante.getApellido(), estudiante.getEdad(),
                estudiante.getCedula(), estudiante.getGrupo(), estudiante.isBeca(),
                estudiante.isActividad() });
        tablaEncontrado.setModel(modelo);
        this.usuario = 1;
        usuarioEncontrado.persona = (Estudiante) estudiante;
    }

    public usuarioEncontrado(Profesor profesor) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Correo");
        modelo.addColumn("Cedula");
        modelo.addColumn("Estado");
        modelo.addColumn("Salario");
        modelo.addRow(new Object[] { profesor.getNombre(), profesor.getApellido(), profesor.getCorreo(),
                profesor.getCedula(), profesor.isActividad(), profesor.getSalario() });
        tablaEncontrado.setModel(modelo);
        this.usuario = 2;
        usuarioEncontrado.persona = (Profesor) profesor;
    }

    public usuarioEncontrado(Cocinero cocinero) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Cedula");
        modelo.addColumn("Estado");
        modelo.addColumn("Salario");
        modelo.addRow(new Object[] { cocinero.getNombre(), cocinero.getApellido(), cocinero.getCedula(),
                cocinero.isActividad(), cocinero.getSalario() });
        tablaEncontrado.setModel(modelo);
        this.usuario = 3;
        usuarioEncontrado.persona = (Cocinero) cocinero;
    }

    public static Persona getPersona() {
        return persona;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEncontrado = new javax.swing.JTable();
        volver = new com.k33ptoo.components.KButton();
        editarBtn1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 153));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEncontrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEncontrado);
        if (tablaEncontrado.getColumnModel().getColumnCount() > 0) {
            tablaEncontrado.getColumnModel().getColumn(0).setResizable(false);
            tablaEncontrado.getColumnModel().getColumn(1).setResizable(false);
            tablaEncontrado.getColumnModel().getColumn(2).setResizable(false);
            tablaEncontrado.getColumnModel().getColumn(3).setResizable(false);
        }

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 12, 399, 89));

        volver.setText("Volver");
        volver.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        volver.setkEndColor(new java.awt.Color(102, 102, 102));
        volver.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        volver.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        volver.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        volver.setkStartColor(new java.awt.Color(51, 51, 51));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        kGradientPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, 30));

        editarBtn1.setText("Editar");
        editarBtn1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        editarBtn1.setkEndColor(new java.awt.Color(51, 51, 51));
        editarBtn1.setkHoverColor(new java.awt.Color(102, 102, 102));
        editarBtn1.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        editarBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        editarBtn1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        editarBtn1.setkStartColor(new java.awt.Color(51, 51, 51));
        editarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtn1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(editarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_volverActionPerformed
        dispose();
    }// GEN-LAST:event_volverActionPerformed

    private void editarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarBtn1ActionPerformed
        switch (usuario) {
            case 1:
                dispose();
                editarEstudiante editarEstudiante = new editarEstudiante();
                editarEstudiante.setVisible(true);
                editarEstudiante.setLocationRelativeTo(null);
                break;
            case 2:
                dispose();
                editarProfesor editarProfesor = new editarProfesor();
                editarProfesor.setVisible(true);
                editarProfesor.setLocationRelativeTo(null);
                break;
            case 3:
                dispose();
                editarCocinero editarCocinero = new editarCocinero();
                editarCocinero.setVisible(true);
                editarCocinero.setLocationRelativeTo(null);
                break;
        }
    }// GEN-LAST:event_editarBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton editarBtn1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tablaEncontrado;
    private com.k33ptoo.components.KButton volver;
    // End of variables declaration//GEN-END:variables
}
